item {
name: 'CheckBox'
  id: 1
}

item {
name: 'TextBox'
  id: 2
}

item {
name: 'Label'
  id: 3
}

item {
name: 'Button'
  id: 4
}

item {
name: 'TextArea'
  id: 5
}

item {
name: 'Selection_List'
  id: 6
}

item {
name: 'RadioButton'
  id: 7
}

